//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgorMarinho_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_trans
    {
        public int trans_id { get; set; }
        public string acc_id { get; set; }
        public string trans_name { get; set; }
        public string trans_value { get; set; }
        public string trans_reg_date { get; set; }
        public string trans_rem_date { get; set; }
        public bool repeat { get; set; }
    }
}
