//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgorMarinho_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int acc_id { get; set; }
        public string acc_name { get; set; }
        public string ins_total { get; set; }
        public string outs_total { get; set; }
        public string user_id { get; set; }
    }
}
