//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgorMarinho_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class reminder
    {
        public int reminder_id { get; set; }
        public string user_id { get; set; }
        public string rem_date { get; set; }
        public string repeat { get; set; }
        public string fullname { get; set; }
        public string acc_name { get; set; }
        public int in_id { get; set; }
        public Nullable<int> out_id { get; set; }
    }
}
