//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1_IgorMarinhoCarneiroRodrigues2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extrato
    {
        public int id_extrato { get; set; }
        public int vl_extrato { get; set; }
        public System.DateTime data_extrato { get; set; }
        public int id_contas { get; set; }
        public int id_cliente { get; set; }
    }
}
